// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_ctrl (
    clk,
    reset,
    TRAN_s_axi_ctrl_AWADDR,
    TRAN_s_axi_ctrl_AWVALID,
    TRAN_s_axi_ctrl_AWREADY,
    TRAN_s_axi_ctrl_WVALID,
    TRAN_s_axi_ctrl_WREADY,
    TRAN_s_axi_ctrl_WDATA,
    TRAN_s_axi_ctrl_WSTRB,
    TRAN_s_axi_ctrl_ARADDR,
    TRAN_s_axi_ctrl_ARVALID,
    TRAN_s_axi_ctrl_ARREADY,
    TRAN_s_axi_ctrl_RVALID,
    TRAN_s_axi_ctrl_RREADY,
    TRAN_s_axi_ctrl_RDATA,
    TRAN_s_axi_ctrl_RRESP,
    TRAN_s_axi_ctrl_BVALID,
    TRAN_s_axi_ctrl_BREADY,
    TRAN_s_axi_ctrl_BRESP,
    TRAN_ctrl_write_data_finish,
    TRAN_ctrl_start_in,
    TRAN_ctrl_idle_out,
    TRAN_ctrl_ready_out,
    TRAN_ctrl_ready_in,
    TRAN_ctrl_done_out,
    TRAN_ctrl_write_start_in   ,
    TRAN_ctrl_write_start_finish,
    TRAN_ctrl_interrupt,
    TRAN_ctrl_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_w1_offset "./c.neural_network.autotvin_w1_offset.dat"
`define TV_IN_w2_offset "./c.neural_network.autotvin_w2_offset.dat"
`define TV_IN_input_offset "./c.neural_network.autotvin_input_offset.dat"
`define TV_IN_b1_offset "./c.neural_network.autotvin_b1_offset.dat"
`define TV_IN_b2_offset "./c.neural_network.autotvin_b2_offset.dat"
`define TV_IN_result_offset "./c.neural_network.autotvin_result_offset.dat"
parameter ADDR_WIDTH = 6;
parameter DATA_WIDTH = 32;
parameter w1_offset_DEPTH = 1;
reg [31 : 0] w1_offset_OPERATE_DEPTH = 0;
parameter w1_offset_c_bitwidth = 32;
parameter w2_offset_DEPTH = 1;
reg [31 : 0] w2_offset_OPERATE_DEPTH = 0;
parameter w2_offset_c_bitwidth = 32;
parameter input_offset_DEPTH = 1;
reg [31 : 0] input_offset_OPERATE_DEPTH = 0;
parameter input_offset_c_bitwidth = 32;
parameter b1_offset_DEPTH = 1;
reg [31 : 0] b1_offset_OPERATE_DEPTH = 0;
parameter b1_offset_c_bitwidth = 32;
parameter b2_offset_DEPTH = 1;
reg [31 : 0] b2_offset_OPERATE_DEPTH = 0;
parameter b2_offset_c_bitwidth = 32;
parameter result_offset_DEPTH = 1;
reg [31 : 0] result_offset_OPERATE_DEPTH = 0;
parameter result_offset_c_bitwidth = 32;
parameter START_ADDR = 0;
parameter neural_network_continue_addr = 0;
parameter neural_network_auto_start_addr = 0;
parameter w1_offset_data_in_addr = 16;
parameter w2_offset_data_in_addr = 24;
parameter input_offset_data_in_addr = 32;
parameter b1_offset_data_in_addr = 40;
parameter b2_offset_data_in_addr = 48;
parameter result_offset_data_in_addr = 56;
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_ctrl_AWADDR;
output  TRAN_s_axi_ctrl_AWVALID;
input  TRAN_s_axi_ctrl_AWREADY;
output  TRAN_s_axi_ctrl_WVALID;
input  TRAN_s_axi_ctrl_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_ctrl_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_ctrl_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_ctrl_ARADDR;
output  TRAN_s_axi_ctrl_ARVALID;
input  TRAN_s_axi_ctrl_ARREADY;
input  TRAN_s_axi_ctrl_RVALID;
output  TRAN_s_axi_ctrl_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_ctrl_RDATA;
input [2 - 1 : 0] TRAN_s_axi_ctrl_RRESP;
input  TRAN_s_axi_ctrl_BVALID;
output  TRAN_s_axi_ctrl_BREADY;
input [2 - 1 : 0] TRAN_s_axi_ctrl_BRESP;
output TRAN_ctrl_write_data_finish;
input     clk;
input     reset;
input     TRAN_ctrl_start_in;
output    TRAN_ctrl_done_out;
output    TRAN_ctrl_ready_out;
input     TRAN_ctrl_ready_in;
output    TRAN_ctrl_idle_out;
input  TRAN_ctrl_write_start_in   ;
output TRAN_ctrl_write_start_finish;
input     TRAN_ctrl_interrupt;
input     TRAN_ctrl_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] mem_w1_offset [w1_offset_DEPTH - 1 : 0];
reg w1_offset_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_w2_offset [w2_offset_DEPTH - 1 : 0];
reg w2_offset_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_input_offset [input_offset_DEPTH - 1 : 0];
reg input_offset_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_b1_offset [b1_offset_DEPTH - 1 : 0];
reg b1_offset_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_b2_offset [b2_offset_DEPTH - 1 : 0];
reg b2_offset_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_result_offset [result_offset_DEPTH - 1 : 0];
reg result_offset_write_data_finish;
reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
reg process_4_finish = 0;
reg process_5_finish = 0;
reg process_6_finish = 0;
reg process_7_finish = 0;
//write w1_offset reg
reg [31 : 0] write_w1_offset_count = 0;
reg write_w1_offset_run_flag = 0;
reg write_one_w1_offset_data_done = 0;
//write w2_offset reg
reg [31 : 0] write_w2_offset_count = 0;
reg write_w2_offset_run_flag = 0;
reg write_one_w2_offset_data_done = 0;
//write input_offset reg
reg [31 : 0] write_input_offset_count = 0;
reg write_input_offset_run_flag = 0;
reg write_one_input_offset_data_done = 0;
//write b1_offset reg
reg [31 : 0] write_b1_offset_count = 0;
reg write_b1_offset_run_flag = 0;
reg write_one_b1_offset_data_done = 0;
//write b2_offset reg
reg [31 : 0] write_b2_offset_count = 0;
reg write_b2_offset_run_flag = 0;
reg write_one_b2_offset_data_done = 0;
//write result_offset reg
reg [31 : 0] write_result_offset_count = 0;
reg write_result_offset_run_flag = 0;
reg write_one_result_offset_data_done = 0;
reg [31 : 0] write_start_count = 0;
reg write_start_run_flag = 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_ctrl_AWADDR = AWADDR_reg;
assign TRAN_s_axi_ctrl_AWVALID = AWVALID_reg;
assign TRAN_s_axi_ctrl_WVALID = WVALID_reg;
assign TRAN_s_axi_ctrl_WDATA = WDATA_reg;
assign TRAN_s_axi_ctrl_WSTRB = WSTRB_reg;
assign TRAN_s_axi_ctrl_ARADDR = ARADDR_reg;
assign TRAN_s_axi_ctrl_ARVALID = ARVALID_reg;
assign TRAN_s_axi_ctrl_RREADY = RREADY_reg;
assign TRAN_s_axi_ctrl_BREADY = BREADY_reg;
assign TRAN_ctrl_write_start_finish = AESL_write_start_finish;
assign TRAN_ctrl_done_out = AESL_done_index_reg;
assign TRAN_ctrl_ready_out = AESL_ready_out_index_reg;
assign TRAN_ctrl_idle_out = AESL_idle_index_reg;
assign TRAN_ctrl_write_data_finish = 1 & w1_offset_write_data_finish & w2_offset_write_data_finish & input_offset_write_data_finish & b1_offset_write_data_finish & b2_offset_write_data_finish & result_offset_write_data_finish;
always @(TRAN_ctrl_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_ctrl_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish or process_4_finish or process_5_finish or process_6_finish or process_7_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 4 && process_4_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 5 && process_5_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 6 && process_6_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 7 && process_7_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_ctrl_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_ctrl_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_ctrl_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_ctrl_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_ctrl_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_ctrl_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_ctrl_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_ctrl_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        w1_offset_write_data_finish <= 0;
        write_w1_offset_run_flag <= 0; 
        write_w1_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (w1_offset_c_bitwidth, w1_offset_DEPTH, w1_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            w1_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_w1_offset_run_flag <= 1; 
            write_w1_offset_count = 0;
        end
        if (write_one_w1_offset_data_done === 1) begin
            write_w1_offset_count = write_w1_offset_count + 1;
            if (write_w1_offset_count == w1_offset_OPERATE_DEPTH) begin
                write_w1_offset_run_flag <= 0; 
                w1_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_w1_offset
    integer write_w1_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] w1_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = w1_offset_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_w1_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write w1_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (w1_offset_c_bitwidth < 32) begin
                        w1_offset_data_tmp_reg = mem_w1_offset[write_w1_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < w1_offset_c_bitwidth) begin
                                w1_offset_data_tmp_reg[j] = mem_w1_offset[write_w1_offset_count][i*32 + j];
                            end
                            else begin
                                w1_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (w1_offset_data_in_addr + write_w1_offset_count * four_byte_num * 4 + i * 4, w1_offset_data_tmp_reg, write_w1_offset_resp);
                end
                process_busy = 0;
                write_one_w1_offset_data_done <= 1;
                @(posedge clk);
                write_one_w1_offset_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        w2_offset_write_data_finish <= 0;
        write_w2_offset_run_flag <= 0; 
        write_w2_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (w2_offset_c_bitwidth, w2_offset_DEPTH, w2_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            w2_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_w2_offset_run_flag <= 1; 
            write_w2_offset_count = 0;
        end
        if (write_one_w2_offset_data_done === 1) begin
            write_w2_offset_count = write_w2_offset_count + 1;
            if (write_w2_offset_count == w2_offset_OPERATE_DEPTH) begin
                write_w2_offset_run_flag <= 0; 
                w2_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_w2_offset
    integer write_w2_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] w2_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = w2_offset_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_w2_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write w2_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (w2_offset_c_bitwidth < 32) begin
                        w2_offset_data_tmp_reg = mem_w2_offset[write_w2_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < w2_offset_c_bitwidth) begin
                                w2_offset_data_tmp_reg[j] = mem_w2_offset[write_w2_offset_count][i*32 + j];
                            end
                            else begin
                                w2_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (w2_offset_data_in_addr + write_w2_offset_count * four_byte_num * 4 + i * 4, w2_offset_data_tmp_reg, write_w2_offset_resp);
                end
                process_busy = 0;
                write_one_w2_offset_data_done <= 1;
                @(posedge clk);
                write_one_w2_offset_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        input_offset_write_data_finish <= 0;
        write_input_offset_run_flag <= 0; 
        write_input_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (input_offset_c_bitwidth, input_offset_DEPTH, input_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            input_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_input_offset_run_flag <= 1; 
            write_input_offset_count = 0;
        end
        if (write_one_input_offset_data_done === 1) begin
            write_input_offset_count = write_input_offset_count + 1;
            if (write_input_offset_count == input_offset_OPERATE_DEPTH) begin
                write_input_offset_run_flag <= 0; 
                input_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_input_offset
    integer write_input_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] input_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = input_offset_c_bitwidth;
    process_num = 3;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_3_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_input_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write input_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (input_offset_c_bitwidth < 32) begin
                        input_offset_data_tmp_reg = mem_input_offset[write_input_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < input_offset_c_bitwidth) begin
                                input_offset_data_tmp_reg[j] = mem_input_offset[write_input_offset_count][i*32 + j];
                            end
                            else begin
                                input_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (input_offset_data_in_addr + write_input_offset_count * four_byte_num * 4 + i * 4, input_offset_data_tmp_reg, write_input_offset_resp);
                end
                process_busy = 0;
                write_one_input_offset_data_done <= 1;
                @(posedge clk);
                write_one_input_offset_data_done <= 0;
            end   
            process_3_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        b1_offset_write_data_finish <= 0;
        write_b1_offset_run_flag <= 0; 
        write_b1_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (b1_offset_c_bitwidth, b1_offset_DEPTH, b1_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            b1_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_b1_offset_run_flag <= 1; 
            write_b1_offset_count = 0;
        end
        if (write_one_b1_offset_data_done === 1) begin
            write_b1_offset_count = write_b1_offset_count + 1;
            if (write_b1_offset_count == b1_offset_OPERATE_DEPTH) begin
                write_b1_offset_run_flag <= 0; 
                b1_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_b1_offset
    integer write_b1_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] b1_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = b1_offset_c_bitwidth;
    process_num = 4;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_4_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_b1_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write b1_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (b1_offset_c_bitwidth < 32) begin
                        b1_offset_data_tmp_reg = mem_b1_offset[write_b1_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < b1_offset_c_bitwidth) begin
                                b1_offset_data_tmp_reg[j] = mem_b1_offset[write_b1_offset_count][i*32 + j];
                            end
                            else begin
                                b1_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (b1_offset_data_in_addr + write_b1_offset_count * four_byte_num * 4 + i * 4, b1_offset_data_tmp_reg, write_b1_offset_resp);
                end
                process_busy = 0;
                write_one_b1_offset_data_done <= 1;
                @(posedge clk);
                write_one_b1_offset_data_done <= 0;
            end   
            process_4_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        b2_offset_write_data_finish <= 0;
        write_b2_offset_run_flag <= 0; 
        write_b2_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (b2_offset_c_bitwidth, b2_offset_DEPTH, b2_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            b2_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_b2_offset_run_flag <= 1; 
            write_b2_offset_count = 0;
        end
        if (write_one_b2_offset_data_done === 1) begin
            write_b2_offset_count = write_b2_offset_count + 1;
            if (write_b2_offset_count == b2_offset_OPERATE_DEPTH) begin
                write_b2_offset_run_flag <= 0; 
                b2_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_b2_offset
    integer write_b2_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] b2_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = b2_offset_c_bitwidth;
    process_num = 5;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_5_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_b2_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write b2_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (b2_offset_c_bitwidth < 32) begin
                        b2_offset_data_tmp_reg = mem_b2_offset[write_b2_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < b2_offset_c_bitwidth) begin
                                b2_offset_data_tmp_reg[j] = mem_b2_offset[write_b2_offset_count][i*32 + j];
                            end
                            else begin
                                b2_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (b2_offset_data_in_addr + write_b2_offset_count * four_byte_num * 4 + i * 4, b2_offset_data_tmp_reg, write_b2_offset_resp);
                end
                process_busy = 0;
                write_one_b2_offset_data_done <= 1;
                @(posedge clk);
                write_one_b2_offset_data_done <= 0;
            end   
            process_5_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        result_offset_write_data_finish <= 0;
        write_result_offset_run_flag <= 0; 
        write_result_offset_count = 0;
        count_operate_depth_by_bitwidth_and_depth (result_offset_c_bitwidth, result_offset_DEPTH, result_offset_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_ctrl_start_in === 1) begin
            result_offset_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_result_offset_run_flag <= 1; 
            write_result_offset_count = 0;
        end
        if (write_one_result_offset_data_done === 1) begin
            write_result_offset_count = write_result_offset_count + 1;
            if (write_result_offset_count == result_offset_OPERATE_DEPTH) begin
                write_result_offset_run_flag <= 0; 
                result_offset_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_result_offset
    integer write_result_offset_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] result_offset_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = result_offset_c_bitwidth;
    process_num = 6;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_6_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_result_offset_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write result_offset data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (result_offset_c_bitwidth < 32) begin
                        result_offset_data_tmp_reg = mem_result_offset[write_result_offset_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < result_offset_c_bitwidth) begin
                                result_offset_data_tmp_reg[j] = mem_result_offset[write_result_offset_count][i*32 + j];
                            end
                            else begin
                                result_offset_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (result_offset_data_in_addr + write_result_offset_count * four_byte_num * 4 + i * 4, result_offset_data_tmp_reg, write_result_offset_resp);
                end
                process_busy = 0;
                write_one_result_offset_data_done <= 1;
                @(posedge clk);
                write_one_result_offset_data_done <= 0;
            end   
            process_6_finish <= 1;
        end
        @(posedge clk);
    end    
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 5) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_ctrl_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 7;
    while (1) begin
        process_7_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_7_finish <= 1;
        end 
        @(posedge clk);
    end
end

//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_w1_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [w1_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (w1_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_w1_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_w1_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < w1_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_w1_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_w1_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_w1_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_w1_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_w1_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_w2_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [w2_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (w2_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_w2_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_w2_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < w2_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_w2_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_w2_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_w2_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_w2_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_w2_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_input_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [input_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (input_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_input_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_input_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < input_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_input_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_input_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_input_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_input_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_input_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_b1_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [b1_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (b1_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_b1_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_b1_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < b1_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_b1_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_b1_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_b1_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_b1_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_b1_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_b2_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [b2_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (b2_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_b2_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_b2_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < b2_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_b2_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_b2_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_b2_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_b2_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_b2_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_result_offset_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [result_offset_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (result_offset_c_bitwidth , factor);
  fp = $fopen(`TV_IN_result_offset ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_result_offset); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < result_offset_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_result_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_result_offset [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_result_offset [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_result_offset [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_result_offset [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
endmodule
