// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      neural_network
`define AUTOTB_DUT_INST AESL_inst_neural_network
`define AUTOTB_TOP      apatb_neural_network_top
`define AUTOTB_LAT_RESULT_FILE "neural_network.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "neural_network.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_neural_network_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_CLOCK_PERIOD_DIV2 1.50

`define AESL_DEPTH_mem_V 1
`define AESL_DEPTH_out_V 1
`define AESL_DEPTH_w1_offset 1
`define AESL_DEPTH_w2_offset 1
`define AESL_DEPTH_input_offset 1
`define AESL_DEPTH_b1_offset 1
`define AESL_DEPTH_b2_offset 1
`define AESL_DEPTH_result_offset 1
`define AUTOTB_TVIN_mem_V  "./c.neural_network.autotvin_mem_V.dat"
`define AUTOTB_TVIN_w1_offset  "./c.neural_network.autotvin_w1_offset.dat"
`define AUTOTB_TVIN_w2_offset  "./c.neural_network.autotvin_w2_offset.dat"
`define AUTOTB_TVIN_input_offset  "./c.neural_network.autotvin_input_offset.dat"
`define AUTOTB_TVIN_b1_offset  "./c.neural_network.autotvin_b1_offset.dat"
`define AUTOTB_TVIN_b2_offset  "./c.neural_network.autotvin_b2_offset.dat"
`define AUTOTB_TVIN_result_offset  "./c.neural_network.autotvin_result_offset.dat"
`define AUTOTB_TVIN_mem_V_out_wrapc  "./rtl.neural_network.autotvin_mem_V.dat"
`define AUTOTB_TVIN_w1_offset_out_wrapc  "./rtl.neural_network.autotvin_w1_offset.dat"
`define AUTOTB_TVIN_w2_offset_out_wrapc  "./rtl.neural_network.autotvin_w2_offset.dat"
`define AUTOTB_TVIN_input_offset_out_wrapc  "./rtl.neural_network.autotvin_input_offset.dat"
`define AUTOTB_TVIN_b1_offset_out_wrapc  "./rtl.neural_network.autotvin_b1_offset.dat"
`define AUTOTB_TVIN_b2_offset_out_wrapc  "./rtl.neural_network.autotvin_b2_offset.dat"
`define AUTOTB_TVIN_result_offset_out_wrapc  "./rtl.neural_network.autotvin_result_offset.dat"
`define AUTOTB_TVOUT_out_V  "./c.neural_network.autotvout_out_V.dat"
`define AUTOTB_TVOUT_out_V_out_wrapc  "./impl_rtl.neural_network.autotvout_out_V.dat"
module `AUTOTB_TOP;

parameter AUTOTB_TRANSACTION_NUM = 5;
parameter PROGRESS_TIMEOUT = 10000000;
parameter LATENCY_ESTIMATION = 839235;
parameter LENGTH_mem_V = 8347050;
parameter LENGTH_out_V = 10;
parameter LENGTH_w1_offset = 1;
parameter LENGTH_w2_offset = 1;
parameter LENGTH_input_offset = 1;
parameter LENGTH_b1_offset = 1;
parameter LENGTH_b2_offset = 1;
parameter LENGTH_result_offset = 1;

task read_token;
    input integer fp;
    output reg [183 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end
endtask

task post_check;
    input integer fp1;
    input integer fp2;
    reg [183 : 0] token1;
    reg [183 : 0] token2;
    reg [183 : 0] golden;
    reg [183 : 0] result;
    integer ret;
    begin
        read_token(fp1, token1);
        read_token(fp2, token2);
        if (token1 != "[[[runtime]]]" || token2 != "[[[runtime]]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
            $finish;
        end
        read_token(fp1, token1);
        read_token(fp2, token2);
        while (token1 != "[[[/runtime]]]" && token2 != "[[[/runtime]]]") begin
            if (token1 != "[[transaction]]" || token2 != "[[transaction]]") begin
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
            end
            read_token(fp1, token1);  // skip transaction number
            read_token(fp2, token2);  // skip transaction number
              read_token(fp1, token1);
              read_token(fp2, token2);
            while(token1 != "[[/transaction]]" && token2 != "[[/transaction]]") begin
                ret = $sscanf(token1, "0x%x", golden);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                ret = $sscanf(token2, "0x%x", result);
                  if (ret != 1) begin
                      $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                  end
                if(golden != result) begin
                      $display("%x (expected) vs. %x (actual) - mismatch", golden, result);
                    $display("ERROR: Simulation using HLS TB failed.");
                      $finish;
                end
                  read_token(fp1, token1);
                  read_token(fp2, token2);
            end
              read_token(fp1, token1);
              read_token(fp2, token2);
        end
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg tb_continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
wire [5 : 0] ctrl_AWADDR;
wire  ctrl_AWVALID;
wire  ctrl_AWREADY;
wire  ctrl_WVALID;
wire  ctrl_WREADY;
wire [31 : 0] ctrl_WDATA;
wire [3 : 0] ctrl_WSTRB;
wire [5 : 0] ctrl_ARADDR;
wire  ctrl_ARVALID;
wire  ctrl_ARREADY;
wire  ctrl_RVALID;
wire  ctrl_RREADY;
wire [31 : 0] ctrl_RDATA;
wire [1 : 0] ctrl_RRESP;
wire  ctrl_BVALID;
wire  ctrl_BREADY;
wire [1 : 0] ctrl_BRESP;
wire  ctrl_INTERRUPT;
wire  mem_V_AWVALID;
wire  mem_V_AWREADY;
wire [31 : 0] mem_V_AWADDR;
wire [0 : 0] mem_V_AWID;
wire [7 : 0] mem_V_AWLEN;
wire [2 : 0] mem_V_AWSIZE;
wire [1 : 0] mem_V_AWBURST;
wire [1 : 0] mem_V_AWLOCK;
wire [3 : 0] mem_V_AWCACHE;
wire [2 : 0] mem_V_AWPROT;
wire [3 : 0] mem_V_AWQOS;
wire [3 : 0] mem_V_AWREGION;
wire [0 : 0] mem_V_AWUSER;
wire  mem_V_WVALID;
wire  mem_V_WREADY;
wire [31 : 0] mem_V_WDATA;
wire [3 : 0] mem_V_WSTRB;
wire  mem_V_WLAST;
wire [0 : 0] mem_V_WID;
wire [0 : 0] mem_V_WUSER;
wire  mem_V_ARVALID;
wire  mem_V_ARREADY;
wire [31 : 0] mem_V_ARADDR;
wire [0 : 0] mem_V_ARID;
wire [7 : 0] mem_V_ARLEN;
wire [2 : 0] mem_V_ARSIZE;
wire [1 : 0] mem_V_ARBURST;
wire [1 : 0] mem_V_ARLOCK;
wire [3 : 0] mem_V_ARCACHE;
wire [2 : 0] mem_V_ARPROT;
wire [3 : 0] mem_V_ARQOS;
wire [3 : 0] mem_V_ARREGION;
wire [0 : 0] mem_V_ARUSER;
wire  mem_V_RVALID;
wire  mem_V_RREADY;
wire [31 : 0] mem_V_RDATA;
wire  mem_V_RLAST;
wire [0 : 0] mem_V_RID;
wire [0 : 0] mem_V_RUSER;
wire [1 : 0] mem_V_RRESP;
wire  mem_V_BVALID;
wire  mem_V_BREADY;
wire [1 : 0] mem_V_BRESP;
wire [0 : 0] mem_V_BID;
wire [0 : 0] mem_V_BUSER;
wire  out_V_AWVALID;
wire  out_V_AWREADY;
wire [31 : 0] out_V_AWADDR;
wire [0 : 0] out_V_AWID;
wire [7 : 0] out_V_AWLEN;
wire [2 : 0] out_V_AWSIZE;
wire [1 : 0] out_V_AWBURST;
wire [1 : 0] out_V_AWLOCK;
wire [3 : 0] out_V_AWCACHE;
wire [2 : 0] out_V_AWPROT;
wire [3 : 0] out_V_AWQOS;
wire [3 : 0] out_V_AWREGION;
wire [0 : 0] out_V_AWUSER;
wire  out_V_WVALID;
wire  out_V_WREADY;
wire [31 : 0] out_V_WDATA;
wire [3 : 0] out_V_WSTRB;
wire  out_V_WLAST;
wire [0 : 0] out_V_WID;
wire [0 : 0] out_V_WUSER;
wire  out_V_ARVALID;
wire  out_V_ARREADY;
wire [31 : 0] out_V_ARADDR;
wire [0 : 0] out_V_ARID;
wire [7 : 0] out_V_ARLEN;
wire [2 : 0] out_V_ARSIZE;
wire [1 : 0] out_V_ARBURST;
wire [1 : 0] out_V_ARLOCK;
wire [3 : 0] out_V_ARCACHE;
wire [2 : 0] out_V_ARPROT;
wire [3 : 0] out_V_ARQOS;
wire [3 : 0] out_V_ARREGION;
wire [0 : 0] out_V_ARUSER;
wire  out_V_RVALID;
wire  out_V_RREADY;
wire [31 : 0] out_V_RDATA;
wire  out_V_RLAST;
wire [0 : 0] out_V_RID;
wire [0 : 0] out_V_RUSER;
wire [1 : 0] out_V_RRESP;
wire  out_V_BVALID;
wire  out_V_BREADY;
wire [1 : 0] out_V_BRESP;
wire [0 : 0] out_V_BID;
wire [0 : 0] out_V_BUSER;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;
wire ctrl_write_data_finish;
wire AESL_slave_start;
wire AESL_slave_write_start_in;
wire AESL_slave_write_start_finish;
reg AESL_slave_ready;
wire AESL_slave_output_done;
reg ready_rise = 0;
reg start_rise = 0;
reg slave_start_status = 0;
reg slave_done_status = 0;

wire ap_clk;
wire ap_rst_n;
wire ap_rst_n_n;

`AUTOTB_DUT `AUTOTB_DUT_INST(
    .s_axi_ctrl_AWADDR(ctrl_AWADDR),
    .s_axi_ctrl_AWVALID(ctrl_AWVALID),
    .s_axi_ctrl_AWREADY(ctrl_AWREADY),
    .s_axi_ctrl_WVALID(ctrl_WVALID),
    .s_axi_ctrl_WREADY(ctrl_WREADY),
    .s_axi_ctrl_WDATA(ctrl_WDATA),
    .s_axi_ctrl_WSTRB(ctrl_WSTRB),
    .s_axi_ctrl_ARADDR(ctrl_ARADDR),
    .s_axi_ctrl_ARVALID(ctrl_ARVALID),
    .s_axi_ctrl_ARREADY(ctrl_ARREADY),
    .s_axi_ctrl_RVALID(ctrl_RVALID),
    .s_axi_ctrl_RREADY(ctrl_RREADY),
    .s_axi_ctrl_RDATA(ctrl_RDATA),
    .s_axi_ctrl_RRESP(ctrl_RRESP),
    .s_axi_ctrl_BVALID(ctrl_BVALID),
    .s_axi_ctrl_BREADY(ctrl_BREADY),
    .s_axi_ctrl_BRESP(ctrl_BRESP),
    .interrupt(ctrl_INTERRUPT),
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .m_axi_mem_V_AWVALID(mem_V_AWVALID),
    .m_axi_mem_V_AWREADY(mem_V_AWREADY),
    .m_axi_mem_V_AWADDR(mem_V_AWADDR),
    .m_axi_mem_V_AWID(mem_V_AWID),
    .m_axi_mem_V_AWLEN(mem_V_AWLEN),
    .m_axi_mem_V_AWSIZE(mem_V_AWSIZE),
    .m_axi_mem_V_AWBURST(mem_V_AWBURST),
    .m_axi_mem_V_AWLOCK(mem_V_AWLOCK),
    .m_axi_mem_V_AWCACHE(mem_V_AWCACHE),
    .m_axi_mem_V_AWPROT(mem_V_AWPROT),
    .m_axi_mem_V_AWQOS(mem_V_AWQOS),
    .m_axi_mem_V_AWREGION(mem_V_AWREGION),
    .m_axi_mem_V_AWUSER(mem_V_AWUSER),
    .m_axi_mem_V_WVALID(mem_V_WVALID),
    .m_axi_mem_V_WREADY(mem_V_WREADY),
    .m_axi_mem_V_WDATA(mem_V_WDATA),
    .m_axi_mem_V_WSTRB(mem_V_WSTRB),
    .m_axi_mem_V_WLAST(mem_V_WLAST),
    .m_axi_mem_V_WID(mem_V_WID),
    .m_axi_mem_V_WUSER(mem_V_WUSER),
    .m_axi_mem_V_ARVALID(mem_V_ARVALID),
    .m_axi_mem_V_ARREADY(mem_V_ARREADY),
    .m_axi_mem_V_ARADDR(mem_V_ARADDR),
    .m_axi_mem_V_ARID(mem_V_ARID),
    .m_axi_mem_V_ARLEN(mem_V_ARLEN),
    .m_axi_mem_V_ARSIZE(mem_V_ARSIZE),
    .m_axi_mem_V_ARBURST(mem_V_ARBURST),
    .m_axi_mem_V_ARLOCK(mem_V_ARLOCK),
    .m_axi_mem_V_ARCACHE(mem_V_ARCACHE),
    .m_axi_mem_V_ARPROT(mem_V_ARPROT),
    .m_axi_mem_V_ARQOS(mem_V_ARQOS),
    .m_axi_mem_V_ARREGION(mem_V_ARREGION),
    .m_axi_mem_V_ARUSER(mem_V_ARUSER),
    .m_axi_mem_V_RVALID(mem_V_RVALID),
    .m_axi_mem_V_RREADY(mem_V_RREADY),
    .m_axi_mem_V_RDATA(mem_V_RDATA),
    .m_axi_mem_V_RLAST(mem_V_RLAST),
    .m_axi_mem_V_RID(mem_V_RID),
    .m_axi_mem_V_RUSER(mem_V_RUSER),
    .m_axi_mem_V_RRESP(mem_V_RRESP),
    .m_axi_mem_V_BVALID(mem_V_BVALID),
    .m_axi_mem_V_BREADY(mem_V_BREADY),
    .m_axi_mem_V_BRESP(mem_V_BRESP),
    .m_axi_mem_V_BID(mem_V_BID),
    .m_axi_mem_V_BUSER(mem_V_BUSER),
    .m_axi_out_V_AWVALID(out_V_AWVALID),
    .m_axi_out_V_AWREADY(out_V_AWREADY),
    .m_axi_out_V_AWADDR(out_V_AWADDR),
    .m_axi_out_V_AWID(out_V_AWID),
    .m_axi_out_V_AWLEN(out_V_AWLEN),
    .m_axi_out_V_AWSIZE(out_V_AWSIZE),
    .m_axi_out_V_AWBURST(out_V_AWBURST),
    .m_axi_out_V_AWLOCK(out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(out_V_AWCACHE),
    .m_axi_out_V_AWPROT(out_V_AWPROT),
    .m_axi_out_V_AWQOS(out_V_AWQOS),
    .m_axi_out_V_AWREGION(out_V_AWREGION),
    .m_axi_out_V_AWUSER(out_V_AWUSER),
    .m_axi_out_V_WVALID(out_V_WVALID),
    .m_axi_out_V_WREADY(out_V_WREADY),
    .m_axi_out_V_WDATA(out_V_WDATA),
    .m_axi_out_V_WSTRB(out_V_WSTRB),
    .m_axi_out_V_WLAST(out_V_WLAST),
    .m_axi_out_V_WID(out_V_WID),
    .m_axi_out_V_WUSER(out_V_WUSER),
    .m_axi_out_V_ARVALID(out_V_ARVALID),
    .m_axi_out_V_ARREADY(out_V_ARREADY),
    .m_axi_out_V_ARADDR(out_V_ARADDR),
    .m_axi_out_V_ARID(out_V_ARID),
    .m_axi_out_V_ARLEN(out_V_ARLEN),
    .m_axi_out_V_ARSIZE(out_V_ARSIZE),
    .m_axi_out_V_ARBURST(out_V_ARBURST),
    .m_axi_out_V_ARLOCK(out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(out_V_ARCACHE),
    .m_axi_out_V_ARPROT(out_V_ARPROT),
    .m_axi_out_V_ARQOS(out_V_ARQOS),
    .m_axi_out_V_ARREGION(out_V_ARREGION),
    .m_axi_out_V_ARUSER(out_V_ARUSER),
    .m_axi_out_V_RVALID(out_V_RVALID),
    .m_axi_out_V_RREADY(out_V_RREADY),
    .m_axi_out_V_RDATA(out_V_RDATA),
    .m_axi_out_V_RLAST(out_V_RLAST),
    .m_axi_out_V_RID(out_V_RID),
    .m_axi_out_V_RUSER(out_V_RUSER),
    .m_axi_out_V_RRESP(out_V_RRESP),
    .m_axi_out_V_BVALID(out_V_BVALID),
    .m_axi_out_V_BREADY(out_V_BREADY),
    .m_axi_out_V_BRESP(out_V_BRESP),
    .m_axi_out_V_BID(out_V_BID),
    .m_axi_out_V_BUSER(out_V_BUSER));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst_n = AESL_reset;
assign ap_rst_n_n = ~AESL_reset;
assign AESL_reset = rst;
assign AESL_start = start;
assign AESL_ce = ce;
assign AESL_continue = tb_continue;
  assign AESL_slave_write_start_in = slave_start_status  & ctrl_write_data_finish;
  assign AESL_slave_start = AESL_slave_write_start_finish;
  assign AESL_done = slave_done_status ;

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        slave_start_status <= 1;
    end
    else begin
        if (AESL_start == 1 ) begin
            start_rise = 1;
        end
        if (start_rise == 1 && AESL_done == 1 ) begin
            slave_start_status <= 1;
        end
        if (AESL_slave_write_start_in == 1) begin 
            slave_start_status <= 0;
            start_rise = 0;
        end
    end
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
    begin
        AESL_slave_ready <= 0;
        ready_rise = 0;
    end
    else begin
        if (AESL_ready == 1 ) begin
            ready_rise = 1;
        end
        if (ready_rise == 1 && AESL_done_delay == 1 ) begin
            AESL_slave_ready <= 1;
        end
        if (AESL_slave_ready == 1) begin 
            AESL_slave_ready <= 0;
            ready_rise = 0;
        end
    end
end

always @ (posedge AESL_clock)
begin
    if (AESL_done == 1) begin
        slave_done_status <= 0;
    end
    else if (AESL_slave_output_done == 1 ) begin
        slave_done_status <= 1;
    end
end








wire    AESL_axi_master_mem_V_ready;
wire    AESL_axi_master_mem_V_done;
AESL_axi_master_mem_V AESL_AXI_MASTER_mem_V(
    .clk   (AESL_clock),
    .reset (AESL_reset),
    .TRAN_mem_V_AWVALID (mem_V_AWVALID),
    .TRAN_mem_V_AWREADY (mem_V_AWREADY),
    .TRAN_mem_V_AWADDR (mem_V_AWADDR),
    .TRAN_mem_V_AWID (mem_V_AWID),
    .TRAN_mem_V_AWLEN (mem_V_AWLEN),
    .TRAN_mem_V_AWSIZE (mem_V_AWSIZE),
    .TRAN_mem_V_AWBURST (mem_V_AWBURST),
    .TRAN_mem_V_AWLOCK (mem_V_AWLOCK),
    .TRAN_mem_V_AWCACHE (mem_V_AWCACHE),
    .TRAN_mem_V_AWPROT (mem_V_AWPROT),
    .TRAN_mem_V_AWQOS (mem_V_AWQOS),
    .TRAN_mem_V_AWREGION (mem_V_AWREGION),
    .TRAN_mem_V_AWUSER (mem_V_AWUSER),
    .TRAN_mem_V_WVALID (mem_V_WVALID),
    .TRAN_mem_V_WREADY (mem_V_WREADY),
    .TRAN_mem_V_WDATA (mem_V_WDATA),
    .TRAN_mem_V_WSTRB (mem_V_WSTRB),
    .TRAN_mem_V_WLAST (mem_V_WLAST),
    .TRAN_mem_V_WID (mem_V_WID),
    .TRAN_mem_V_WUSER (mem_V_WUSER),
    .TRAN_mem_V_ARVALID (mem_V_ARVALID),
    .TRAN_mem_V_ARREADY (mem_V_ARREADY),
    .TRAN_mem_V_ARADDR (mem_V_ARADDR),
    .TRAN_mem_V_ARID (mem_V_ARID),
    .TRAN_mem_V_ARLEN (mem_V_ARLEN),
    .TRAN_mem_V_ARSIZE (mem_V_ARSIZE),
    .TRAN_mem_V_ARBURST (mem_V_ARBURST),
    .TRAN_mem_V_ARLOCK (mem_V_ARLOCK),
    .TRAN_mem_V_ARCACHE (mem_V_ARCACHE),
    .TRAN_mem_V_ARPROT (mem_V_ARPROT),
    .TRAN_mem_V_ARQOS (mem_V_ARQOS),
    .TRAN_mem_V_ARREGION (mem_V_ARREGION),
    .TRAN_mem_V_ARUSER (mem_V_ARUSER),
    .TRAN_mem_V_RVALID (mem_V_RVALID),
    .TRAN_mem_V_RREADY (mem_V_RREADY),
    .TRAN_mem_V_RDATA (mem_V_RDATA),
    .TRAN_mem_V_RLAST (mem_V_RLAST),
    .TRAN_mem_V_RID (mem_V_RID),
    .TRAN_mem_V_RUSER (mem_V_RUSER),
    .TRAN_mem_V_RRESP (mem_V_RRESP),
    .TRAN_mem_V_BVALID (mem_V_BVALID),
    .TRAN_mem_V_BREADY (mem_V_BREADY),
    .TRAN_mem_V_BRESP (mem_V_BRESP),
    .TRAN_mem_V_BID (mem_V_BID),
    .TRAN_mem_V_BUSER (mem_V_BUSER),
    .ready (AESL_axi_master_mem_V_ready),
    .done  (AESL_axi_master_mem_V_done)
);
assign    AESL_axi_master_mem_V_ready    =   ready;
assign    AESL_axi_master_mem_V_done    =   AESL_done_delay;
wire    AESL_axi_master_out_V_ready;
wire    AESL_axi_master_out_V_done;
AESL_axi_master_out_V AESL_AXI_MASTER_out_V(
    .clk   (AESL_clock),
    .reset (AESL_reset),
    .TRAN_out_V_AWVALID (out_V_AWVALID),
    .TRAN_out_V_AWREADY (out_V_AWREADY),
    .TRAN_out_V_AWADDR (out_V_AWADDR),
    .TRAN_out_V_AWID (out_V_AWID),
    .TRAN_out_V_AWLEN (out_V_AWLEN),
    .TRAN_out_V_AWSIZE (out_V_AWSIZE),
    .TRAN_out_V_AWBURST (out_V_AWBURST),
    .TRAN_out_V_AWLOCK (out_V_AWLOCK),
    .TRAN_out_V_AWCACHE (out_V_AWCACHE),
    .TRAN_out_V_AWPROT (out_V_AWPROT),
    .TRAN_out_V_AWQOS (out_V_AWQOS),
    .TRAN_out_V_AWREGION (out_V_AWREGION),
    .TRAN_out_V_AWUSER (out_V_AWUSER),
    .TRAN_out_V_WVALID (out_V_WVALID),
    .TRAN_out_V_WREADY (out_V_WREADY),
    .TRAN_out_V_WDATA (out_V_WDATA),
    .TRAN_out_V_WSTRB (out_V_WSTRB),
    .TRAN_out_V_WLAST (out_V_WLAST),
    .TRAN_out_V_WID (out_V_WID),
    .TRAN_out_V_WUSER (out_V_WUSER),
    .TRAN_out_V_ARVALID (out_V_ARVALID),
    .TRAN_out_V_ARREADY (out_V_ARREADY),
    .TRAN_out_V_ARADDR (out_V_ARADDR),
    .TRAN_out_V_ARID (out_V_ARID),
    .TRAN_out_V_ARLEN (out_V_ARLEN),
    .TRAN_out_V_ARSIZE (out_V_ARSIZE),
    .TRAN_out_V_ARBURST (out_V_ARBURST),
    .TRAN_out_V_ARLOCK (out_V_ARLOCK),
    .TRAN_out_V_ARCACHE (out_V_ARCACHE),
    .TRAN_out_V_ARPROT (out_V_ARPROT),
    .TRAN_out_V_ARQOS (out_V_ARQOS),
    .TRAN_out_V_ARREGION (out_V_ARREGION),
    .TRAN_out_V_ARUSER (out_V_ARUSER),
    .TRAN_out_V_RVALID (out_V_RVALID),
    .TRAN_out_V_RREADY (out_V_RREADY),
    .TRAN_out_V_RDATA (out_V_RDATA),
    .TRAN_out_V_RLAST (out_V_RLAST),
    .TRAN_out_V_RID (out_V_RID),
    .TRAN_out_V_RUSER (out_V_RUSER),
    .TRAN_out_V_RRESP (out_V_RRESP),
    .TRAN_out_V_BVALID (out_V_BVALID),
    .TRAN_out_V_BREADY (out_V_BREADY),
    .TRAN_out_V_BRESP (out_V_BRESP),
    .TRAN_out_V_BID (out_V_BID),
    .TRAN_out_V_BUSER (out_V_BUSER),
    .ready (AESL_axi_master_out_V_ready),
    .done  (AESL_axi_master_out_V_done)
);
assign    AESL_axi_master_out_V_ready    =   ready;
assign    AESL_axi_master_out_V_done    =   AESL_done_delay;

AESL_axi_slave_ctrl AESL_AXI_SLAVE_ctrl(
    .clk   (AESL_clock),
    .reset (AESL_reset),
    .TRAN_s_axi_ctrl_AWADDR (ctrl_AWADDR),
    .TRAN_s_axi_ctrl_AWVALID (ctrl_AWVALID),
    .TRAN_s_axi_ctrl_AWREADY (ctrl_AWREADY),
    .TRAN_s_axi_ctrl_WVALID (ctrl_WVALID),
    .TRAN_s_axi_ctrl_WREADY (ctrl_WREADY),
    .TRAN_s_axi_ctrl_WDATA (ctrl_WDATA),
    .TRAN_s_axi_ctrl_WSTRB (ctrl_WSTRB),
    .TRAN_s_axi_ctrl_ARADDR (ctrl_ARADDR),
    .TRAN_s_axi_ctrl_ARVALID (ctrl_ARVALID),
    .TRAN_s_axi_ctrl_ARREADY (ctrl_ARREADY),
    .TRAN_s_axi_ctrl_RVALID (ctrl_RVALID),
    .TRAN_s_axi_ctrl_RREADY (ctrl_RREADY),
    .TRAN_s_axi_ctrl_RDATA (ctrl_RDATA),
    .TRAN_s_axi_ctrl_RRESP (ctrl_RRESP),
    .TRAN_s_axi_ctrl_BVALID (ctrl_BVALID),
    .TRAN_s_axi_ctrl_BREADY (ctrl_BREADY),
    .TRAN_s_axi_ctrl_BRESP (ctrl_BRESP),
    .TRAN_ctrl_interrupt (ctrl_INTERRUPT),
    .TRAN_ctrl_write_data_finish(ctrl_write_data_finish),
    .TRAN_ctrl_ready_out (AESL_ready),
    .TRAN_ctrl_ready_in (AESL_slave_ready),
    .TRAN_ctrl_done_out (AESL_slave_output_done),
    .TRAN_ctrl_idle_out (AESL_idle),
    .TRAN_ctrl_write_start_in     (AESL_slave_write_start_in),
    .TRAN_ctrl_write_start_finish (AESL_slave_write_start_finish),
    .TRAN_ctrl_transaction_done_in (AESL_done_delay),
    .TRAN_ctrl_start_in  (AESL_slave_start)
);

initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 1);
    while(AESL_ready_cnt != AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

    event next_trigger_ready_cnt;
    
    initial begin : gen_ready_cnt
        ready_cnt = 0;
        wait (AESL_reset === 1);
        forever begin
            @ (posedge AESL_clock);
            if (ready == 1) begin
                if (ready_cnt < AUTOTB_TRANSACTION_NUM) begin
                    ready_cnt = ready_cnt + 1;
                end
            end
            -> next_trigger_ready_cnt;
        end
    end
    
    wire all_finish = (done_cnt == AUTOTB_TRANSACTION_NUM);
    
    // done_cnt
    always @ (posedge AESL_clock) begin
        if (~AESL_reset) begin
            done_cnt <= 0;
        end else begin
            if (AESL_done == 1) begin
                if (done_cnt < AUTOTB_TRANSACTION_NUM) begin
                    done_cnt <= done_cnt + 1;
                end
            end
        end
    end
    
    initial begin : finish_simulation
        integer fp1;
        integer fp2;
        wait (all_finish == 1);
        // last transaction is saved at negedge right after last done
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        $display("Simulation Passed.");
        $finish;
    end
    
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_mem_V;
reg [31:0] size_mem_V;
reg [31:0] size_mem_V_backup;
reg end_w1_offset;
reg [31:0] size_w1_offset;
reg [31:0] size_w1_offset_backup;
reg end_w2_offset;
reg [31:0] size_w2_offset;
reg [31:0] size_w2_offset_backup;
reg end_input_offset;
reg [31:0] size_input_offset;
reg [31:0] size_input_offset_backup;
reg end_b1_offset;
reg [31:0] size_b1_offset;
reg [31:0] size_b1_offset_backup;
reg end_b2_offset;
reg [31:0] size_b2_offset;
reg [31:0] size_b2_offset_backup;
reg end_result_offset;
reg [31:0] size_result_offset;
reg [31:0] size_result_offset_backup;
reg end_out_V;
reg [31:0] size_out_V;
reg [31:0] size_out_V_backup;

initial begin : initial_process
    integer proc_rand;
    rst = 0;
    # 100;
    repeat(3) @ (posedge AESL_clock);
    rst = 1;
end
initial begin : start_process
    integer proc_rand;
    reg [31:0] start_cnt;
    ce = 1;
    start = 0;
    start_cnt = 0;
    wait (AESL_reset === 1);
    @ (posedge AESL_clock);
    #0 start = 1;
    start_cnt = start_cnt + 1;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt >= AUTOTB_TRANSACTION_NUM) begin
            // keep pushing garbage in
            #0 start = 1;
        end
        if (AESL_ready) begin
            start_cnt = start_cnt + 1;
        end
    end
end

always @(AESL_done)
begin
    tb_continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset === 0)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end

reg dump_tvout_finish_out_V;

initial begin : dump_tvout_runtime_sign_out_V
    integer fp;
    dump_tvout_finish_out_V = 0;
    fp = $fopen(`AUTOTB_TVOUT_out_V_out_wrapc, "w");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_out_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    $fclose(fp);
    wait (done_cnt == AUTOTB_TRANSACTION_NUM);
    // last transaction is saved at negedge right after last done
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    @ (posedge AESL_clock);
    fp = $fopen(`AUTOTB_TVOUT_out_V_out_wrapc, "a");
    if (fp == 0) begin
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_out_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
    dump_tvout_finish_out_V = 1;
end


////////////////////////////////////////////
// progress and performance
////////////////////////////////////////////

task wait_start();
    while (~AESL_start) begin
        @ (posedge AESL_clock);
    end
endtask

reg [31:0] clk_cnt = 0;
reg AESL_ready_p1;
reg AESL_start_p1;

always @ (posedge AESL_clock) begin
    clk_cnt <= clk_cnt + 1;
    AESL_ready_p1 <= AESL_ready;
    AESL_start_p1 <= AESL_start;
end

reg [31:0] start_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] start_cnt;
reg [31:0] ready_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] ap_ready_cnt;
reg [31:0] finish_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] finish_cnt;
event report_progress;

initial begin
    start_cnt = 0;
    finish_cnt = 0;
    ap_ready_cnt = 0;
    wait (AESL_reset == 1);
    wait_start();
    start_timestamp[start_cnt] = clk_cnt;
    start_cnt = start_cnt + 1;
    if (AESL_done) begin
        finish_timestamp[finish_cnt] = clk_cnt;
        finish_cnt = finish_cnt + 1;
    end
    -> report_progress;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt < AUTOTB_TRANSACTION_NUM) begin
            if ((AESL_start && AESL_ready_p1)||(AESL_start && ~AESL_start_p1)) begin
                start_timestamp[start_cnt] = clk_cnt;
                start_cnt = start_cnt + 1;
            end
        end
        if (ap_ready_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_start_p1 && AESL_ready_p1) begin
                ready_timestamp[ap_ready_cnt] = clk_cnt;
                ap_ready_cnt = ap_ready_cnt + 1;
            end
        end
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                finish_timestamp[finish_cnt] = clk_cnt;
                finish_cnt = finish_cnt + 1;
            end
        end
        -> report_progress;
    end
end

reg [31:0] progress_timeout;

initial begin : simulation_progress
    real intra_progress;
    wait (AESL_reset == 1);
    progress_timeout = PROGRESS_TIMEOUT;
    $display("////////////////////////////////////////////////////////////////////////////////////");
    $display("// Inter-Transaction Progress: Completed Transaction / Total Transaction");
    $display("// Intra-Transaction Progress: Measured Latency / Latency Estimation * 100%%");
    $display("//");
    $display("// RTL Simulation : \"Inter-Transaction Progress\" [\"Intra-Transaction Progress\"] @ \"Simulation Time\"");
    $display("////////////////////////////////////////////////////////////////////////////////////");
    print_progress();
    while (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
        @ (report_progress);
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                print_progress();
                progress_timeout = PROGRESS_TIMEOUT;
            end else begin
                if (progress_timeout == 0) begin
                    print_progress();
                    progress_timeout = PROGRESS_TIMEOUT;
                end else begin
                    progress_timeout = progress_timeout - 1;
                end
            end
        end
    end
    print_progress();
    $display("////////////////////////////////////////////////////////////////////////////////////");
    calculate_performance();
end

task get_intra_progress(output real intra_progress);
    begin
        if (start_cnt > finish_cnt) begin
            intra_progress = clk_cnt - start_timestamp[finish_cnt];
        end else if(finish_cnt > 0) begin
            intra_progress = LATENCY_ESTIMATION;
        end else begin
            intra_progress = 0;
        end
        intra_progress = intra_progress / LATENCY_ESTIMATION;
    end
endtask

task print_progress();
    real intra_progress;
    begin
        if (LATENCY_ESTIMATION > 0) begin
            get_intra_progress(intra_progress);
            $display("// RTL Simulation : %0d / %0d [%2.2f%%] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, intra_progress * 100, $time);
        end else begin
            $display("// RTL Simulation : %0d / %0d [n/a] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, $time);
        end
    end
endtask

task calculate_performance();
    integer i;
    integer fp;
    reg [31:0] latency [0:AUTOTB_TRANSACTION_NUM - 1];
    reg [31:0] latency_min;
    reg [31:0] latency_max;
    reg [31:0] latency_total;
    reg [31:0] latency_average;
    reg [31:0] interval [0:AUTOTB_TRANSACTION_NUM - 2];
    reg [31:0] interval_min;
    reg [31:0] interval_max;
    reg [31:0] interval_total;
    reg [31:0] interval_average;
    begin
        latency_min = -1;
        latency_max = 0;
        latency_total = 0;
        interval_min = -1;
        interval_max = 0;
        interval_total = 0;

        for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
            // calculate latency
            latency[i] = finish_timestamp[i] - start_timestamp[i];
            if (latency[i] > latency_max) latency_max = latency[i];
            if (latency[i] < latency_min) latency_min = latency[i];
            latency_total = latency_total + latency[i];
            // calculate interval
            if (AUTOTB_TRANSACTION_NUM == 1) begin
                interval[i] = 0;
                interval_max = 0;
                interval_min = 0;
                interval_total = 0;
            end else if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                interval[i] = finish_timestamp[i] - start_timestamp[i]+1;
                if (interval[i] > interval_max) interval_max = interval[i];
                if (interval[i] < interval_min) interval_min = interval[i];
                interval_total = interval_total + interval[i];
            end
        end

        latency_average = latency_total / AUTOTB_TRANSACTION_NUM;
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            interval_average = 0;
        end else begin
            interval_average = interval_total / (AUTOTB_TRANSACTION_NUM - 1);
        end

        fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

        $fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latency_max);
        $fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latency_min);
        $fdisplay(fp, "$AVER_LATENCY = \"%0d\"", latency_average);
        $fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", interval_max);
        $fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", interval_min);
        $fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", interval_average);

        $fclose(fp);

        fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");

        $fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            i = 0;
            $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
        end else begin
            for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
                if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                    $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
                end else begin
                    $fdisplay(fp, "transaction%8d:%16d               x", i, latency[i]);
                end
            end
        end

        $fclose(fp);
    end
endtask


////////////////////////////////////////////
// Dependence Check
////////////////////////////////////////////

`ifndef POST_SYN

`endif

endmodule
