// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _packer_HH_
#define _packer_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "packer_packet_useibs.h"

namespace ap_rtl {

struct packer : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > stream_in_V_V_dout;
    sc_in< sc_logic > stream_in_V_V_empty_n;
    sc_out< sc_logic > stream_in_V_V_read;
    sc_out< sc_lv<16> > sdata_out_TDATA;
    sc_out< sc_logic > sdata_out_TVALID;
    sc_in< sc_logic > sdata_out_TREADY;
    sc_out< sc_lv<2> > sdata_out_TKEEP;
    sc_out< sc_lv<2> > sdata_out_TSTRB;
    sc_out< sc_lv<1> > sdata_out_TUSER;
    sc_out< sc_lv<1> > sdata_out_TLAST;
    sc_out< sc_lv<1> > sdata_out_TID;
    sc_out< sc_lv<1> > sdata_out_TDEST;


    // Module declarations
    packer(sc_module_name name);
    SC_HAS_PROCESS(packer);

    ~packer();

    sc_trace_file* mVcdFile;

    packer_packet_useibs* packet_user_V_U;
    packer_packet_useibs* packet_id_V_U;
    packer_packet_useibs* packet_dest_V_U;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<16> > stream_out_V_data_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_data_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_data_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_data_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_data_V_1_ack_out;
    sc_signal< sc_lv<16> > stream_out_V_data_V_1_payload_A;
    sc_signal< sc_lv<16> > stream_out_V_data_V_1_payload_B;
    sc_signal< sc_logic > stream_out_V_data_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_data_V_1_sel_wr;
    sc_signal< sc_logic > stream_out_V_data_V_1_sel;
    sc_signal< sc_logic > stream_out_V_data_V_1_load_A;
    sc_signal< sc_logic > stream_out_V_data_V_1_load_B;
    sc_signal< sc_lv<2> > stream_out_V_data_V_1_state;
    sc_signal< sc_logic > stream_out_V_data_V_1_state_cmp_full;
    sc_signal< sc_lv<2> > stream_out_V_keep_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_keep_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_keep_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_keep_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_keep_V_1_ack_out;
    sc_signal< sc_logic > stream_out_V_keep_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_keep_V_1_sel;
    sc_signal< sc_lv<2> > stream_out_V_keep_V_1_state;
    sc_signal< sc_lv<2> > stream_out_V_strb_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_strb_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_strb_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_strb_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_strb_V_1_ack_out;
    sc_signal< sc_logic > stream_out_V_strb_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_strb_V_1_sel;
    sc_signal< sc_lv<2> > stream_out_V_strb_V_1_state;
    sc_signal< sc_lv<1> > stream_out_V_user_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_user_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_user_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_user_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_user_V_1_ack_out;
    sc_signal< sc_lv<1> > stream_out_V_user_V_1_payload_A;
    sc_signal< sc_lv<1> > stream_out_V_user_V_1_payload_B;
    sc_signal< sc_logic > stream_out_V_user_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_user_V_1_sel_wr;
    sc_signal< sc_logic > stream_out_V_user_V_1_sel;
    sc_signal< sc_logic > stream_out_V_user_V_1_load_A;
    sc_signal< sc_logic > stream_out_V_user_V_1_load_B;
    sc_signal< sc_lv<2> > stream_out_V_user_V_1_state;
    sc_signal< sc_logic > stream_out_V_user_V_1_state_cmp_full;
    sc_signal< sc_lv<1> > stream_out_V_last_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_last_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_last_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_last_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_last_V_1_ack_out;
    sc_signal< sc_lv<1> > stream_out_V_last_V_1_payload_A;
    sc_signal< sc_lv<1> > stream_out_V_last_V_1_payload_B;
    sc_signal< sc_logic > stream_out_V_last_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_last_V_1_sel_wr;
    sc_signal< sc_logic > stream_out_V_last_V_1_sel;
    sc_signal< sc_logic > stream_out_V_last_V_1_load_A;
    sc_signal< sc_logic > stream_out_V_last_V_1_load_B;
    sc_signal< sc_lv<2> > stream_out_V_last_V_1_state;
    sc_signal< sc_logic > stream_out_V_last_V_1_state_cmp_full;
    sc_signal< sc_lv<1> > stream_out_V_id_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_id_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_id_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_id_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_id_V_1_ack_out;
    sc_signal< sc_lv<1> > stream_out_V_id_V_1_payload_A;
    sc_signal< sc_lv<1> > stream_out_V_id_V_1_payload_B;
    sc_signal< sc_logic > stream_out_V_id_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_id_V_1_sel_wr;
    sc_signal< sc_logic > stream_out_V_id_V_1_sel;
    sc_signal< sc_logic > stream_out_V_id_V_1_load_A;
    sc_signal< sc_logic > stream_out_V_id_V_1_load_B;
    sc_signal< sc_lv<2> > stream_out_V_id_V_1_state;
    sc_signal< sc_logic > stream_out_V_id_V_1_state_cmp_full;
    sc_signal< sc_lv<1> > stream_out_V_dest_V_1_data_out;
    sc_signal< sc_logic > stream_out_V_dest_V_1_vld_in;
    sc_signal< sc_logic > stream_out_V_dest_V_1_vld_out;
    sc_signal< sc_logic > stream_out_V_dest_V_1_ack_in;
    sc_signal< sc_logic > stream_out_V_dest_V_1_ack_out;
    sc_signal< sc_lv<1> > stream_out_V_dest_V_1_payload_A;
    sc_signal< sc_lv<1> > stream_out_V_dest_V_1_payload_B;
    sc_signal< sc_logic > stream_out_V_dest_V_1_sel_rd;
    sc_signal< sc_logic > stream_out_V_dest_V_1_sel_wr;
    sc_signal< sc_logic > stream_out_V_dest_V_1_sel;
    sc_signal< sc_logic > stream_out_V_dest_V_1_load_A;
    sc_signal< sc_logic > stream_out_V_dest_V_1_load_B;
    sc_signal< sc_lv<2> > stream_out_V_dest_V_1_state;
    sc_signal< sc_logic > stream_out_V_dest_V_1_state_cmp_full;
    sc_signal< sc_logic > stream_in_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_reg_198;
    sc_signal< sc_logic > sdata_out_TDATA_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > ap_reg_pp0_iter1_exitcond_reg_198;
    sc_signal< sc_lv<4> > i_reg_162;
    sc_signal< sc_lv<1> > exitcond_fu_173_p2;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_io;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<4> > i_2_fu_179_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_last_V_fu_192_p2;
    sc_signal< sc_lv<1> > tmp_last_V_reg_207;
    sc_signal< sc_lv<1> > packet_user_V_q0;
    sc_signal< sc_lv<1> > packet_id_V_q0;
    sc_signal< sc_lv<1> > packet_dest_V_q0;
    sc_signal< bool > ap_block_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_lv<4> > packet_user_V_address0;
    sc_signal< sc_logic > packet_user_V_ce0;
    sc_signal< sc_lv<4> > packet_id_V_address0;
    sc_signal< sc_logic > packet_id_V_ce0;
    sc_signal< sc_lv<4> > packet_dest_V_address0;
    sc_signal< sc_logic > packet_dest_V_ce0;
    sc_signal< sc_lv<64> > tmp_fu_185_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< bool > ap_block_state5;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_io();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_exitcond_fu_173_p2();
    void thread_i_2_fu_179_p2();
    void thread_packet_dest_V_address0();
    void thread_packet_dest_V_ce0();
    void thread_packet_id_V_address0();
    void thread_packet_id_V_ce0();
    void thread_packet_user_V_address0();
    void thread_packet_user_V_ce0();
    void thread_sdata_out_TDATA();
    void thread_sdata_out_TDATA_blk_n();
    void thread_sdata_out_TDEST();
    void thread_sdata_out_TID();
    void thread_sdata_out_TKEEP();
    void thread_sdata_out_TLAST();
    void thread_sdata_out_TSTRB();
    void thread_sdata_out_TUSER();
    void thread_sdata_out_TVALID();
    void thread_stream_in_V_V_blk_n();
    void thread_stream_in_V_V_read();
    void thread_stream_out_V_data_V_1_ack_in();
    void thread_stream_out_V_data_V_1_ack_out();
    void thread_stream_out_V_data_V_1_data_out();
    void thread_stream_out_V_data_V_1_load_A();
    void thread_stream_out_V_data_V_1_load_B();
    void thread_stream_out_V_data_V_1_sel();
    void thread_stream_out_V_data_V_1_state_cmp_full();
    void thread_stream_out_V_data_V_1_vld_in();
    void thread_stream_out_V_data_V_1_vld_out();
    void thread_stream_out_V_dest_V_1_ack_in();
    void thread_stream_out_V_dest_V_1_ack_out();
    void thread_stream_out_V_dest_V_1_data_out();
    void thread_stream_out_V_dest_V_1_load_A();
    void thread_stream_out_V_dest_V_1_load_B();
    void thread_stream_out_V_dest_V_1_sel();
    void thread_stream_out_V_dest_V_1_state_cmp_full();
    void thread_stream_out_V_dest_V_1_vld_in();
    void thread_stream_out_V_dest_V_1_vld_out();
    void thread_stream_out_V_id_V_1_ack_in();
    void thread_stream_out_V_id_V_1_ack_out();
    void thread_stream_out_V_id_V_1_data_out();
    void thread_stream_out_V_id_V_1_load_A();
    void thread_stream_out_V_id_V_1_load_B();
    void thread_stream_out_V_id_V_1_sel();
    void thread_stream_out_V_id_V_1_state_cmp_full();
    void thread_stream_out_V_id_V_1_vld_in();
    void thread_stream_out_V_id_V_1_vld_out();
    void thread_stream_out_V_keep_V_1_ack_in();
    void thread_stream_out_V_keep_V_1_ack_out();
    void thread_stream_out_V_keep_V_1_data_out();
    void thread_stream_out_V_keep_V_1_sel();
    void thread_stream_out_V_keep_V_1_vld_in();
    void thread_stream_out_V_keep_V_1_vld_out();
    void thread_stream_out_V_last_V_1_ack_in();
    void thread_stream_out_V_last_V_1_ack_out();
    void thread_stream_out_V_last_V_1_data_out();
    void thread_stream_out_V_last_V_1_load_A();
    void thread_stream_out_V_last_V_1_load_B();
    void thread_stream_out_V_last_V_1_sel();
    void thread_stream_out_V_last_V_1_state_cmp_full();
    void thread_stream_out_V_last_V_1_vld_in();
    void thread_stream_out_V_last_V_1_vld_out();
    void thread_stream_out_V_strb_V_1_ack_in();
    void thread_stream_out_V_strb_V_1_ack_out();
    void thread_stream_out_V_strb_V_1_data_out();
    void thread_stream_out_V_strb_V_1_sel();
    void thread_stream_out_V_strb_V_1_vld_in();
    void thread_stream_out_V_strb_V_1_vld_out();
    void thread_stream_out_V_user_V_1_ack_in();
    void thread_stream_out_V_user_V_1_ack_out();
    void thread_stream_out_V_user_V_1_data_out();
    void thread_stream_out_V_user_V_1_load_A();
    void thread_stream_out_V_user_V_1_load_B();
    void thread_stream_out_V_user_V_1_sel();
    void thread_stream_out_V_user_V_1_state_cmp_full();
    void thread_stream_out_V_user_V_1_vld_in();
    void thread_stream_out_V_user_V_1_vld_out();
    void thread_tmp_fu_185_p1();
    void thread_tmp_last_V_fu_192_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
