# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1.xci
# IP: The module: 'base_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1.xci
# IP: The module: 'base_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xbili/Code/FPGA/vivado-projects/hls_fp32_naive/hls_fp32_naive.srcs/sources_1/bd/base/ip/base_auto_us_1/base_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
