lappend pragmaStatus0 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network/InitL1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network/InitL2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network/Layer1DotProduct" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network/Layer2DotProduct" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "neural_network/ReLU" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "CompleteRegister::get_result/GetMantissa" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "CompleteRegister::get_result/FlipMantissa" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "CompleteRegister::multiply_accumulate" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'CompleteRegister::multiply_accumulate' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/neural_network.cpp" location "CompleteRegister::get_result" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "INTERFACE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network/InitL1" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network/InitL2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network/Layer1DotProduct" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network/Layer2DotProduct" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "neural_network/ReLU" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'neural_network' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "CompleteRegister::get_result/GetMantissa" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "UNROLL" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "CompleteRegister::get_result/FlipMantissa" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "CompleteRegister::multiply_accumulate" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'CompleteRegister::multiply_accumulate' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "PIPELINE" source "/home/xbili/Code/FPGA/deep-learning-fpga/src/hls/exact_dot_product/complete_register.cpp" location "CompleteRegister::get_result" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'CompleteRegister::get_result' does not exist in any synthesis source file."}
