// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_neural_network (
ap_int<8>* mem,
ap_int<32>* out,
unsigned int w1_offset,
unsigned int w2_offset,
unsigned int input_offset,
unsigned int b1_offset,
unsigned int b2_offset,
unsigned int result_offset);
