// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of w1_offset
//        bit 31~0 - w1_offset[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of b1_offset
//        bit 31~0 - b1_offset[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of w2_offset
//        bit 31~0 - w2_offset[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of b2_offset
//        bit 31~0 - b2_offset[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of input_offset
//        bit 31~0 - input_offset[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of result_offset
//        bit 31~0 - result_offset[31:0] (Read/Write)
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XNEURAL_NETWORK_AXILITES_ADDR_AP_CTRL            0x00
#define XNEURAL_NETWORK_AXILITES_ADDR_GIE                0x04
#define XNEURAL_NETWORK_AXILITES_ADDR_IER                0x08
#define XNEURAL_NETWORK_AXILITES_ADDR_ISR                0x0c
#define XNEURAL_NETWORK_AXILITES_ADDR_W1_OFFSET_DATA     0x10
#define XNEURAL_NETWORK_AXILITES_BITS_W1_OFFSET_DATA     32
#define XNEURAL_NETWORK_AXILITES_ADDR_B1_OFFSET_DATA     0x18
#define XNEURAL_NETWORK_AXILITES_BITS_B1_OFFSET_DATA     32
#define XNEURAL_NETWORK_AXILITES_ADDR_W2_OFFSET_DATA     0x20
#define XNEURAL_NETWORK_AXILITES_BITS_W2_OFFSET_DATA     32
#define XNEURAL_NETWORK_AXILITES_ADDR_B2_OFFSET_DATA     0x28
#define XNEURAL_NETWORK_AXILITES_BITS_B2_OFFSET_DATA     32
#define XNEURAL_NETWORK_AXILITES_ADDR_INPUT_OFFSET_DATA  0x30
#define XNEURAL_NETWORK_AXILITES_BITS_INPUT_OFFSET_DATA  32
#define XNEURAL_NETWORK_AXILITES_ADDR_RESULT_OFFSET_DATA 0x38
#define XNEURAL_NETWORK_AXILITES_BITS_RESULT_OFFSET_DATA 32

